#pragma once

#include "media/TransportStream.h"

#include <array>
#include <chrono>
#include <cstddef>
#include <cstdint>
#include <deque>

namespace dvbstreamer5::media::mpegts {

// WISI Chameleon interoperable MPEG-over-UDP layout: 7 * 188 = 1316 bytes.
inline constexpr std::size_t kPacketsPerCbrDatagram = 7;
using CbrDatagram = std::array<Packet, kPacketsPerCbrDatagram>;

// Fixed transport clock for WISI Chameleon. Source NULL packets are removed and
// regenerated by this shaper. Useful packets keep their original bytes/PCR/PTS/DTS,
// but are distributed over the configured CBR slots using the useful-payload rate
// derived from source PCR spacing. This prevents buffered HTTP/SRT/HLS bursts from
// compressing PCR spacing on output.
class CbrTsPacer {
public:
    explicit CbrTsPacer(std::uint64_t targetBitrate);

    bool canEnqueue(const Packet& packet) const noexcept;
    bool enqueue(const Packet& packet);
    bool nextDatagram(
        std::chrono::steady_clock::time_point now,
        CbrDatagram& datagram);

    bool started() const noexcept;
    bool timingLocked() const noexcept;
    std::chrono::steady_clock::time_point nextDeadline() const noexcept;
    std::uint64_t targetBitrate() const noexcept;
    std::uint64_t sourcePayloadBitrate() const noexcept;
    std::size_t queuedPackets() const noexcept;
    std::size_t queuedBytes() const noexcept;
    static constexpr std::size_t maximumQueuedBytes() noexcept {
        return kMaximumQueuedBytes;
    }

private:
    struct QueuedPacket {
        Packet packet {};
        std::uint64_t sequence = 0;
        std::uint64_t sourceRate = 0;
    };

    void advanceDeadline() noexcept;
    void makeNullPacket(Packet& packet) noexcept;
    void observeArrival(std::chrono::steady_clock::time_point now) noexcept;
    void observePcr(const Packet& packet, std::uint64_t sequence) noexcept;
    void annotatePcrInterval(
        std::uint64_t firstSequence,
        std::uint64_t lastSequence,
        std::uint64_t sourceRate) noexcept;
    std::uint64_t rateForNextPacket() const noexcept;
    static bool isNullPacket(const Packet& packet) noexcept;
    static bool readPcr(
        const Packet& packet,
        std::uint64_t& pcrTicks,
        bool& discontinuity) noexcept;

    static constexpr std::size_t kMaximumQueuedBytes = 8 * 1024 * 1024;
    static constexpr std::uint64_t kMinimumBitrate = 100000;
    static constexpr std::uint64_t kMaximumBitrate = 200000000;

    std::uint64_t targetBitrate_;
    std::deque<QueuedPacket> queuedPackets_;
    std::chrono::steady_clock::time_point nextDeadline_ {};
    std::uint64_t pacingRemainder_ = 0;
    std::uint64_t usefulToken_ = 0;
    std::uint8_t nullContinuityCounter_ = 0;
    bool started_ = false;

    std::uint64_t nextSequence_ = 1;
    bool havePreviousPcr_ = false;
    bool pcrTimingLocked_ = false;
    std::uint64_t previousPcrTicks_ = 0;
    std::uint64_t previousPcrSequence_ = 0;
    std::uint64_t sourcePayloadBitrate_ = 0;

    bool arrivalWindowStarted_ = false;
    std::chrono::steady_clock::time_point arrivalWindowStart_ {};
    std::uint64_t arrivalPackets_ = 0;
    std::uint64_t arrivalPayloadBitrate_ = 0;
};

} // namespace dvbstreamer5::media::mpegts
