#pragma once

#include "media/TransportStream.h"

#include <array>
#include <chrono>
#include <cstddef>
#include <cstdint>
#include <deque>

namespace dvbstreamer5::media::mpegts {

// WISI Chameleon interoperable MPEG-over-UDP layout: 7 * 188 = 1316 bytes.
inline constexpr std::size_t kPacketsPerCbrDatagram = 7;
using CbrDatagram = std::array<Packet, kPacketsPerCbrDatagram>;

// Fixed transport clock for WISI Chameleon.
//
// Source NULL packets are removed and regenerated by this shaper. Useful TS is
// paced from a long PCR-derived media-rate estimate plus a slow reservoir
// controller, so short VBR peaks are absorbed by the queue instead of being
// forced into one literal PCR interval. Source PTS/DTS are preserved. PCR on the
// selected PCR PID is restamped to the actual target-CBR output slot position,
// which is the normal remultiplexer model and makes the PCR clock agree with the
// physical 1316-byte transport clock seen by WISI.
class CbrTsPacer {
public:
    explicit CbrTsPacer(std::uint64_t targetBitrate);

    bool canEnqueue(const Packet& packet) const noexcept;
    bool enqueue(const Packet& packet);
    bool nextDatagram(
        std::chrono::steady_clock::time_point now,
        CbrDatagram& datagram);

    bool started() const noexcept;
    bool timingLocked() const noexcept;
    std::chrono::steady_clock::time_point nextDeadline() const noexcept;
    std::uint64_t targetBitrate() const noexcept;
    std::uint64_t sourcePayloadBitrate() const noexcept;
    std::uint64_t usefulPaceBitrate() const noexcept;
    std::size_t queuedPackets() const noexcept;
    std::size_t queuedBytes() const noexcept;
    std::uint64_t bufferedMediaMilliseconds() const noexcept;
    std::uint64_t sourceOverTargetWindows() const noexcept;
    std::uint64_t pcrRewriteCount() const noexcept;
    std::size_t lastDatagramUsefulPackets() const noexcept;

    // Compatibility with the V167 worker diagnostics. In V168 a non-empty
    // useful queue replaces the old notion of a completed PCR segment, and the
    // old insufficient-segment counter maps to long media-rate windows that are
    // genuinely above the configured transport bitrate.
    std::size_t readySegments() const noexcept;
    std::uint64_t insufficientTargetSegments() const noexcept;

    static constexpr std::size_t maximumQueuedBytes() noexcept {
        return kMaximumQueuedBytes;
    }

private:
    void advanceDeadline() noexcept;
    void makeNullPacket(Packet& packet) noexcept;
    void observeArrival(std::chrono::steady_clock::time_point now) noexcept;
    void observeSourcePcr(const Packet& packet) noexcept;
    void updateUsefulPace(std::chrono::steady_clock::time_point now) noexcept;
    bool restampPcr(Packet& packet, std::uint64_t outputSlot) noexcept;

    static bool isNullPacket(const Packet& packet) noexcept;
    static std::uint16_t packetPid(const Packet& packet) noexcept;
    static bool readPcr(
        const Packet& packet,
        std::uint64_t& pcrTicks,
        bool& discontinuity) noexcept;
    static bool writePcr(Packet& packet, std::uint64_t pcrTicks) noexcept;

    static constexpr std::size_t kMaximumQueuedBytes = 8 * 1024 * 1024;
    static constexpr std::uint64_t kMinimumBitrate = 100000;
    static constexpr std::uint64_t kMaximumBitrate = 200000000;

    std::uint64_t targetBitrate_;
    std::deque<Packet> queuedPackets_;
    std::chrono::steady_clock::time_point nextDeadline_ {};
    std::uint64_t pacingRemainder_ = 0;
    std::uint64_t usefulToken_ = 0;
    std::uint8_t nullContinuityCounter_ = 0;
    bool started_ = false;
    std::size_t lastDatagramUsefulPackets_ = 0;

    // Source media-rate measurement. Count only useful (non-NULL) TS packets.
    std::uint64_t totalUsefulPackets_ = 0;
    bool havePcrPid_ = false;
    std::uint16_t pcrPid_ = 0;
    bool havePreviousSourcePcr_ = false;
    std::uint64_t previousSourcePcrTicks_ = 0;
    std::uint64_t previousSourcePcrPacketCount_ = 0;
    std::uint64_t mediaWindowTicks_ = 0;
    std::uint64_t mediaWindowPackets_ = 0;
    bool pcrTimingLocked_ = false;
    std::uint64_t sourcePayloadBitrate_ = 0;
    std::uint64_t sourceOverTargetWindows_ = 0;

    // Wall-clock fallback for streams without a usable PCR.
    bool arrivalWindowStarted_ = false;
    std::chrono::steady_clock::time_point arrivalWindowStart_ {};
    std::uint64_t arrivalWindowPackets_ = 0;
    std::uint64_t arrivalPayloadBitrate_ = 0;

    // Useful-packet reservoir controller. This only controls real-vs-NULL slot
    // selection; the transport bitrate itself never changes.
    std::uint64_t usefulPaceBitrate_ = 0;
    std::chrono::steady_clock::time_point lastControllerUpdate_ {};

    // Output PCR remultiplexing clock. PCR advances from actual target-CBR TS
    // slot positions, independently of source delivery bursts.
    std::uint64_t outputSlotCounter_ = 0;
    bool haveOutputPcrAnchor_ = false;
    std::uint64_t outputPcrTicks_ = 0;
    std::uint64_t outputPcrSlot_ = 0;
    std::uint64_t pcrRewriteCount_ = 0;
};

} // namespace dvbstreamer5::media::mpegts
